(define-module (venues demo-venue)
  #:use-module (starlet base)
  #:use-module (starlet fixture-library generic))

;; Conventional dimmers (1-48)
(define-public dim1 (patch-fixture! <generic-dimmer> 1))
(define-public dim2 (patch-fixture! <generic-dimmer> 2))
(define-public dim3 (patch-fixture! <generic-dimmer> 3))
(define-public dim4 (patch-fixture! <generic-dimmer> 4))
(define-public dim5 (patch-fixture! <generic-dimmer> 5))
(define-public dim6 (patch-fixture! <generic-dimmer> 6))
(define-public dim7 (patch-fixture! <generic-dimmer> 7))
(define-public dim8 (patch-fixture! <generic-dimmer> 8))
(define-public dim9 (patch-fixture! <generic-dimmer> 9))

(define-public dim10 (patch-fixture! <generic-dimmer> 10))
(define-public dim11 (patch-fixture! <generic-dimmer> 11))
(define-public dim12 (patch-fixture! <generic-dimmer> 12))
(define-public dim13 (patch-fixture! <generic-dimmer> 13))
(define-public dim14 (patch-fixture! <generic-dimmer> 14))
(define-public dim15 (patch-fixture! <generic-dimmer> 15))
(define-public dim16 (patch-fixture! <generic-dimmer> 16))
(define-public dim17 (patch-fixture! <generic-dimmer> 17))
(define-public dim18 (patch-fixture! <generic-dimmer> 18))
(define-public dim19 (patch-fixture! <generic-dimmer> 19))

(define-public dim20 (patch-fixture! <generic-dimmer> 20))
(define-public dim21 (patch-fixture! <generic-dimmer> 21))
(define-public dim22 (patch-fixture! <generic-dimmer> 22))
(define-public dim23 (patch-fixture! <generic-dimmer> 23))
(define-public dim24 (patch-fixture! <generic-dimmer> 24))
(define-public dim25 (patch-fixture! <generic-dimmer> 25))
(define-public dim26 (patch-fixture! <generic-dimmer> 26))
(define-public dim27 (patch-fixture! <generic-dimmer> 27))
(define-public dim28 (patch-fixture! <generic-dimmer> 28))
(define-public dim29 (patch-fixture! <generic-dimmer> 29))

(define-public dim30 (patch-fixture! <generic-dimmer> 30))
(define-public dim31 (patch-fixture! <generic-dimmer> 31))
(define-public dim32 (patch-fixture! <generic-dimmer> 32))
(define-public dim33 (patch-fixture! <generic-dimmer> 33))
(define-public dim34 (patch-fixture! <generic-dimmer> 34))
(define-public dim35 (patch-fixture! <generic-dimmer> 35))
(define-public dim36 (patch-fixture! <generic-dimmer> 36))
(define-public dim37 (patch-fixture! <generic-dimmer> 37))
(define-public dim38 (patch-fixture! <generic-dimmer> 38))
(define-public dim39 (patch-fixture! <generic-dimmer> 39))

(define-public dim40 (patch-fixture! <generic-dimmer> 40))
(define-public dim41 (patch-fixture! <generic-dimmer> 41))
(define-public dim42 (patch-fixture! <generic-dimmer> 42))
(define-public dim43 (patch-fixture! <generic-dimmer> 43))
(define-public dim44 (patch-fixture! <generic-dimmer> 44))
(define-public dim45 (patch-fixture! <generic-dimmer> 45))
(define-public dim46 (patch-fixture! <generic-dimmer> 46))
(define-public dim47 (patch-fixture! <generic-dimmer> 47))
(define-public dim48 (patch-fixture! <generic-dimmer> 48))
